[project]
name = "oshten"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "numpy>=2.3.2",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "websockets>=15.0.1",
]
